

project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "ML Squamish"
  navbar:
    background: primary
    search: true
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - past-events/past-events.qmd
      - about.qmd


files:
  exclude:
    - "**/*.ipynb"
      

format:
  html:
    theme: materia
    css: styles.css
    toc: true



